/**
 * Comprehensive Scale Compatibility Database
 * AI-generated relationships between scales and keys with detailed rationales
 */

export interface ScaleKeyRelationship {
  scaleName: string;
  keyQuality: 'major' | 'minor';
  compatibilityScore: number; // 1-10
  relationship: string;
  rationale: string;
  musicalContext: string;
  recommendedUse: string;
  avoidNotes?: string[];
  targetNotes?: string[];
}

/**
 * Comprehensive database of scale-to-key relationships
 * Each entry contains AI-generated analysis of how a scale relates to major/minor keys
 */
export const SCALE_KEY_RELATIONSHIPS: Record<string, {
  major: ScaleKeyRelationship;
  minor: ScaleKeyRelationship;
}> = {
  'Ionian (Major)': {
    major: {
      scaleName: 'Ionian (Major)',
      keyQuality: 'major',
      compatibilityScore: 10,
      relationship: 'Perfect tonal match',
      rationale: 'This is the defining scale of the major key, containing all diatonic notes with no alterations.',
      musicalContext: 'The foundation of Western harmony, providing complete tonal stability and resolution.',
      recommendedUse: 'Primary scale for all melodic and harmonic material. Use freely over I, IV, and V chords.',
      targetNotes: ['1', '3', '5'],
    },
    minor: {
      scaleName: 'Ionian (Major)',
      keyQuality: 'minor',
      compatibilityScore: 6,
      relationship: 'Relative major relationship',
      rationale: 'Shares all notes with the relative minor key, starting from the 6th degree of this scale.',
      musicalContext: 'Creates brightness and major tonality over minor progressions, useful for modal interchange.',
      recommendedUse: 'Use over bIII chord or for creating major-over-minor color. Works well in verse-chorus contrasts.',
      avoidNotes: ['4'],
    },
  },
  
  'Dorian': {
    major: {
      scaleName: 'Dorian',
      keyQuality: 'major',
      compatibilityScore: 8,
      relationship: 'Second mode of major scale',
      rationale: 'Built on the 2nd degree of the major scale, sharing all notes but emphasizing the ii chord quality.',
      musicalContext: 'Provides sophisticated minor tonality with a raised 6th, perfect for jazz and funk contexts.',
      recommendedUse: 'Excellent over ii chords and minor vamps. The natural 6th creates a brighter minor sound than Aeolian.',
      targetNotes: ['2', '6'],
    },
    minor: {
      scaleName: 'Dorian',
      keyQuality: 'minor',
      compatibilityScore: 9,
      relationship: 'Parallel mode with raised 6th',
      rationale: 'Differs from natural minor by only one note (raised 6th), creating a sophisticated minor sound.',
      musicalContext: 'The go-to minor scale for jazz, rock, and funk. More versatile than Aeolian due to the major 6th.',
      recommendedUse: 'Primary choice for minor key improvisation in jazz and contemporary styles. Works over i and iv chords.',
      targetNotes: ['1', 'b3', '6'],
    },
  },

  'Phrygian': {
    major: {
      scaleName: 'Phrygian',
      keyQuality: 'major',
      compatibilityScore: 7,
      relationship: 'Third mode of major scale',
      rationale: 'Built on the 3rd degree of the major scale, creating a dark minor sound with a distinctive b2.',
      musicalContext: 'Provides Spanish/flamenco flavor with its characteristic half-step root motion.',
      recommendedUse: 'Use over iii chords or for creating exotic, Spanish-influenced passages. The b2 is the signature note.',
      targetNotes: ['b2', 'b6'],
    },
    minor: {
      scaleName: 'Phrygian',
      keyQuality: 'minor',
      compatibilityScore: 8,
      relationship: 'Parallel mode with flattened 2nd',
      rationale: 'Natural minor with a b2, creating the darkest of the church modes with strong Spanish/Middle Eastern character.',
      musicalContext: 'Essential for flamenco, metal, and Middle Eastern music. The b2 creates intense half-step tension.',
      recommendedUse: 'Perfect for dark, exotic minor passages. Emphasize the b2 to b1 resolution. Works over bII chord.',
      targetNotes: ['b2', '1'],
      avoidNotes: ['6'],
    },
  },

  'Lydian': {
    major: {
      scaleName: 'Lydian',
      keyQuality: 'major',
      compatibilityScore: 9,
      relationship: 'Fourth mode with raised 4th',
      rationale: 'Major scale with a #4, creating a dreamy, floating quality without the pull of the perfect 4th.',
      musicalContext: 'The brightest major mode, favored in film scores and jazz for its ethereal, uplifting character.',
      recommendedUse: 'Excellent over IV chords and for creating floating, dreamlike major passages. The #4 is the magic note.',
      targetNotes: ['#4', '7'],
    },
    minor: {
      scaleName: 'Lydian',
      keyQuality: 'minor',
      compatibilityScore: 5,
      relationship: 'Distant relationship via relative minor',
      rationale: 'Creates major tonality over minor keys, useful for modal interchange and brightness.',
      musicalContext: 'Provides unexpected major color over minor progressions, creating tension and release.',
      recommendedUse: 'Use sparingly over bVI chord or for brief major excursions. The #4 can clash with minor tonality.',
      avoidNotes: ['4'],
    },
  },

  'Mixolydian': {
    major: {
      scaleName: 'Mixolydian',
      keyQuality: 'major',
      compatibilityScore: 9,
      relationship: 'Fifth mode with dominant character',
      rationale: 'Major scale with a b7, creating the essential dominant 7th sound central to blues and rock.',
      musicalContext: 'The foundation of blues, rock, and country music. The b7 creates the characteristic dominant tension.',
      recommendedUse: 'Primary scale for V7 chords and blues-based music. The b7 is essential for authentic blues sound.',
      targetNotes: ['1', '3', 'b7'],
    },
    minor: {
      scaleName: 'Mixolydian',
      keyQuality: 'minor',
      compatibilityScore: 6,
      relationship: 'Relative major mode relationship',
      rationale: 'Built on the 5th of the relative major, providing dominant function over minor keys.',
      musicalContext: 'Creates dominant tension in minor keys, especially useful over V7 chords in minor.',
      recommendedUse: 'Use over V7 chords in minor keys. The major 3rd creates the necessary leading tone tension.',
      targetNotes: ['3', 'b7'],
    },
  },

  'Aeolian (Natural Minor)': {
    major: {
      scaleName: 'Aeolian (Natural Minor)',
      keyQuality: 'major',
      compatibilityScore: 8,
      relationship: 'Sixth mode - relative minor',
      rationale: 'Built on the 6th degree of the major scale, sharing all notes but emphasizing minor tonality.',
      musicalContext: 'The natural minor scale, providing the relative minor relationship essential to Western harmony.',
      recommendedUse: 'Perfect over vi chords and for creating minor passages within major keys. All notes are diatonic.',
      targetNotes: ['6', '1', '3'],
    },
    minor: {
      scaleName: 'Aeolian (Natural Minor)',
      keyQuality: 'minor',
      compatibilityScore: 10,
      relationship: 'Perfect tonal match',
      rationale: 'This is the natural minor scale, the fundamental minor tonality in Western music.',
      musicalContext: 'The foundation of minor key harmony, providing complete diatonic framework for minor keys.',
      recommendedUse: 'Primary scale for minor key improvisation. Use freely over i, iv, and v chords.',
      targetNotes: ['1', 'b3', '5'],
    },
  },

  'Locrian': {
    major: {
      scaleName: 'Locrian',
      keyQuality: 'major',
      compatibilityScore: 7,
      relationship: 'Seventh mode - diminished quality',
      rationale: 'Built on the 7th degree, creating a diminished tonality with b2 and b5 for maximum instability.',
      musicalContext: 'The most unstable mode, rarely used as a tonal center but essential for vii° chords.',
      recommendedUse: 'Use exclusively over vii° chords. The b5 creates the diminished quality. Avoid as a tonal center.',
      targetNotes: ['b2', 'b5'],
      avoidNotes: ['5'],
    },
    minor: {
      scaleName: 'Locrian',
      keyQuality: 'minor',
      compatibilityScore: 6,
      relationship: 'Parallel mode with diminished 5th',
      rationale: 'Natural minor with b2 and b5, creating extreme instability and tension.',
      musicalContext: 'Theoretical mode rarely used melodically, but defines the ii°7 chord in minor keys.',
      recommendedUse: 'Use over ii°7 chords in minor. The b5 is essential. Avoid extended melodic passages.',
      targetNotes: ['b2', 'b5'],
      avoidNotes: ['5'],
    },
  },

  'Harmonic Minor': {
    major: {
      scaleName: 'Harmonic Minor',
      keyQuality: 'major',
      compatibilityScore: 5,
      relationship: 'Parallel minor with raised 7th',
      rationale: 'Creates minor tonality with a major 7th, providing strong V-i resolution in minor contexts.',
      musicalContext: 'Classical minor scale with exotic augmented 2nd interval between b6 and 7.',
      recommendedUse: 'Use for modal interchange over vi chords. The raised 7th creates classical minor flavor.',
      avoidNotes: ['b6'],
    },
    minor: {
      scaleName: 'Harmonic Minor',
      keyQuality: 'minor',
      compatibilityScore: 9,
      relationship: 'Classical minor with leading tone',
      rationale: 'Natural minor with raised 7th, creating the essential V7-i resolution in minor keys.',
      musicalContext: 'The foundation of classical minor harmony, with characteristic augmented 2nd (b6 to 7).',
      recommendedUse: 'Primary scale for classical minor progressions. Essential over V7 chords. The raised 7th is crucial.',
      targetNotes: ['7', 'b3', '5'],
    },
  },

  'Melodic Minor': {
    major: {
      scaleName: 'Melodic Minor',
      keyQuality: 'major',
      compatibilityScore: 6,
      relationship: 'Parallel minor with raised 6th and 7th',
      rationale: 'Minor scale with major 6th and 7th, creating a hybrid major-minor sound.',
      musicalContext: 'Jazz minor scale, source of many important jazz modes and altered dominant sounds.',
      recommendedUse: 'Use for sophisticated modal interchange. The raised 6th and 7th create jazz flavor.',
      targetNotes: ['6', '7'],
    },
    minor: {
      scaleName: 'Melodic Minor',
      keyQuality: 'minor',
      compatibilityScore: 9,
      relationship: 'Jazz minor - ascending melodic form',
      rationale: 'Natural minor with raised 6th and 7th, eliminating the augmented 2nd of harmonic minor.',
      musicalContext: 'The jazz minor scale, smoother than harmonic minor and source of crucial jazz modes.',
      recommendedUse: 'Primary jazz minor scale. Use ascending for smooth melodic lines. Essential for modern jazz.',
      targetNotes: ['1', 'b3', '6', '7'],
    },
  },

  'Pentatonic Major': {
    major: {
      scaleName: 'Pentatonic Major',
      keyQuality: 'major',
      compatibilityScore: 10,
      relationship: 'Diatonic subset - safe note selection',
      rationale: 'Contains only the most consonant notes of the major scale (1, 2, 3, 5, 6), avoiding the 4th and 7th.',
      musicalContext: 'Universal scale found in every musical culture, providing guaranteed consonance and melodic strength.',
      recommendedUse: 'Perfect for beginners and pros alike. Cannot play a wrong note. Ideal for rock, blues, and pop solos.',
      targetNotes: ['1', '3', '5'],
    },
    minor: {
      scaleName: 'Pentatonic Major',
      keyQuality: 'minor',
      compatibilityScore: 7,
      relationship: 'Relative major pentatonic',
      rationale: 'Built on the relative major (bIII), shares notes with minor pentatonic but emphasizes major tonality.',
      musicalContext: 'Creates bright, major-over-minor sound popular in rock and blues for contrast.',
      recommendedUse: 'Use over bIII, bVI, and bVII chords. Great for creating major-minor ambiguity in blues.',
      targetNotes: ['bIII', 'bVI'],
    },
  },

  'Pentatonic Minor': {
    major: {
      scaleName: 'Pentatonic Minor',
      keyQuality: 'major',
      compatibilityScore: 8,
      relationship: 'Relative minor pentatonic',
      rationale: 'Built on the 6th degree (vi), providing minor pentatonic color within major keys.',
      musicalContext: 'Essential for blues and rock, creating the characteristic minor-over-major blues sound.',
      recommendedUse: 'Primary scale for blues in major keys. Works over I, IV, and V. The b3 creates the blues feel.',
      targetNotes: ['1', 'b3', '5'],
    },
    minor: {
      scaleName: 'Pentatonic Minor',
      keyQuality: 'minor',
      compatibilityScore: 10,
      relationship: 'Diatonic subset - safe note selection',
      rationale: 'Contains only the most essential minor notes (1, b3, 4, 5, b7), avoiding the unstable 2nd and 6th.',
      musicalContext: 'The foundation of blues, rock, and countless other styles. Universally applicable in minor contexts.',
      recommendedUse: 'Primary scale for minor key improvisation in blues and rock. Cannot play a wrong note.',
      targetNotes: ['1', 'b3', '5'],
    },
  },

  'Blues': {
    major: {
      scaleName: 'Blues',
      keyQuality: 'major',
      compatibilityScore: 9,
      relationship: 'Minor pentatonic with blue note',
      rationale: 'Minor pentatonic with added b5 (blue note), creating the essential blues sound over major chords.',
      musicalContext: 'The defining scale of blues music, with the b5 creating characteristic tension and release.',
      recommendedUse: 'Essential for authentic blues playing. The b5 (blue note) is the signature sound. Bend into it.',
      targetNotes: ['b3', 'b5', 'b7'],
    },
    minor: {
      scaleName: 'Blues',
      keyQuality: 'minor',
      compatibilityScore: 10,
      relationship: 'Minor pentatonic with blue note',
      rationale: 'Minor pentatonic with added b5, creating the complete blues vocabulary in minor keys.',
      musicalContext: 'The complete blues scale, with the b5 providing the essential blues tension.',
      recommendedUse: 'Primary blues scale for minor keys. Emphasize the b5 for authentic blues phrasing.',
      targetNotes: ['1', 'b3', 'b5', 'b7'],
    },
  },

  'Phrygian Dominant': {
    major: {
      scaleName: 'Phrygian Dominant',
      keyQuality: 'major',
      compatibilityScore: 6,
      relationship: '5th mode of harmonic minor',
      rationale: 'Phrygian mode with major 3rd, creating exotic Spanish/Middle Eastern flavor.',
      musicalContext: 'Essential for flamenco and Middle Eastern music, with characteristic b2 and major 3rd.',
      recommendedUse: 'Use over V7 chords in minor keys for Spanish flavor. The b2 and major 3rd are signature notes.',
      targetNotes: ['b2', '3'],
    },
    minor: {
      scaleName: 'Phrygian Dominant',
      keyQuality: 'minor',
      compatibilityScore: 8,
      relationship: 'Dominant scale in harmonic minor',
      rationale: 'Built on the 5th of harmonic minor, providing exotic dominant function with b2 and b6.',
      musicalContext: 'The dominant scale of harmonic minor, essential for flamenco, metal, and Middle Eastern music.',
      recommendedUse: 'Perfect over V7 chords in minor. The b2 creates intense Spanish/Arabic character.',
      targetNotes: ['b2', '3', 'b6'],
    },
  },

  'Lydian Dominant': {
    major: {
      scaleName: 'Lydian Dominant',
      keyQuality: 'major',
      compatibilityScore: 8,
      relationship: '4th mode of melodic minor',
      rationale: 'Mixolydian with #4, combining dominant function with Lydian brightness.',
      musicalContext: 'The jazz dominant scale, providing sophisticated altered dominant sound without extreme tension.',
      recommendedUse: 'Excellent over V7 chords. The #4 adds color without the harshness of b5. Jazz standard.',
      targetNotes: ['3', '#4', 'b7'],
    },
    minor: {
      scaleName: 'Lydian Dominant',
      keyQuality: 'minor',
      compatibilityScore: 7,
      relationship: 'Altered dominant for minor',
      rationale: 'Provides sophisticated dominant color over minor keys with #4 alteration.',
      musicalContext: 'Jazz dominant scale for minor keys, less tense than Super Locrian but more colorful than Mixolydian.',
      recommendedUse: 'Use over V7 chords in jazz minor contexts. The #4 provides sophisticated color.',
      targetNotes: ['3', '#4', 'b7'],
    },
  },

  'Super Locrian': {
    major: {
      scaleName: 'Super Locrian',
      keyQuality: 'major',
      compatibilityScore: 5,
      relationship: '7th mode of melodic minor',
      rationale: 'Highly altered scale with b2, b3, b5, b6, creating maximum dominant tension.',
      musicalContext: 'The altered scale, essential for modern jazz and fusion for extreme dominant alterations.',
      recommendedUse: 'Use over V7alt chords. Contains all possible dominant alterations. Advanced jazz technique.',
      targetNotes: ['b2', 'b5', 'b6'],
      avoidNotes: ['2', '6'],
    },
    minor: {
      scaleName: 'Super Locrian',
      keyQuality: 'minor',
      compatibilityScore: 7,
      relationship: 'Altered dominant for minor',
      rationale: 'The ultimate altered dominant scale, containing all possible alterations (b9, #9, b5, #5).',
      musicalContext: 'Modern jazz altered scale, providing maximum tension over dominant chords in minor.',
      recommendedUse: 'Use over V7alt chords in minor. All alterations available. Resolve to i chord.',
      targetNotes: ['b2', '#2', 'b5'],
    },
  },

  'Dorian ♭2': {
    major: {
      scaleName: 'Dorian ♭2',
      keyQuality: 'major',
      compatibilityScore: 5,
      relationship: '2nd mode of melodic minor',
      rationale: 'Dorian with b2, creating exotic minor sound with Phrygian flavor.',
      musicalContext: 'Jazz mode combining Dorian sophistication with Phrygian darkness.',
      recommendedUse: 'Use for exotic minor color. The b2 adds Phrygian tension to Dorian brightness.',
      targetNotes: ['b2', '6'],
    },
    minor: {
      scaleName: 'Dorian ♭2',
      keyQuality: 'minor',
      compatibilityScore: 7,
      relationship: 'Phrygian with natural 6th',
      rationale: 'Combines Phrygian\'s b2 with Dorian\'s natural 6th for sophisticated minor sound.',
      musicalContext: 'Jazz minor mode, brighter than Phrygian but darker than Dorian.',
      recommendedUse: 'Use over ii chords in minor for exotic color. The natural 6th brightens Phrygian.',
      targetNotes: ['b2', '6'],
    },
  },

  'Lydian Augmented': {
    major: {
      scaleName: 'Lydian Augmented',
      keyQuality: 'major',
      compatibilityScore: 7,
      relationship: '3rd mode of melodic minor',
      rationale: 'Lydian with #5, creating dreamy augmented tonality.',
      musicalContext: 'Ethereal jazz mode, combining Lydian brightness with augmented mystery.',
      recommendedUse: 'Use over Imaj7#5 chords. The #4 and #5 create floating, dreamlike quality.',
      targetNotes: ['#4', '#5'],
    },
    minor: {
      scaleName: 'Lydian Augmented',
      keyQuality: 'minor',
      compatibilityScore: 4,
      relationship: 'Distant augmented relationship',
      rationale: 'Creates major augmented tonality over minor, highly experimental.',
      musicalContext: 'Extreme modal interchange, rarely used but creates unique augmented color.',
      recommendedUse: 'Use sparingly for experimental augmented passages. Very advanced technique.',
      avoidNotes: ['5'],
    },
  },

  'Mixolydian ♭6': {
    major: {
      scaleName: 'Mixolydian ♭6',
      keyQuality: 'major',
      compatibilityScore: 6,
      relationship: '5th mode of melodic minor',
      rationale: 'Mixolydian with b6, adding minor color to dominant function.',
      musicalContext: 'Jazz dominant mode with darker character than standard Mixolydian.',
      recommendedUse: 'Use over V7 chords for darker dominant color. The b6 adds minor inflection.',
      targetNotes: ['3', 'b6', 'b7'],
    },
    minor: {
      scaleName: 'Mixolydian ♭6',
      keyQuality: 'minor',
      compatibilityScore: 7,
      relationship: 'Dominant with minor 6th',
      rationale: 'Provides dominant function with b6 matching minor key character.',
      musicalContext: 'Darker dominant sound for minor keys, bridging major and minor tonalities.',
      recommendedUse: 'Use over V7 chords in minor. The b6 connects to minor tonality.',
      targetNotes: ['3', 'b6', 'b7'],
    },
  },

  'Locrian ♮6': {
    major: {
      scaleName: 'Locrian ♮6',
      keyQuality: 'major',
      compatibilityScore: 5,
      relationship: '2nd mode of harmonic minor',
      rationale: 'Locrian with natural 6th, slightly less unstable than pure Locrian.',
      musicalContext: 'Theoretical mode rarely used melodically, defines ii°7 in harmonic minor.',
      recommendedUse: 'Use over ii°7 chords in harmonic minor contexts. Still highly unstable.',
      targetNotes: ['b2', 'b5', '6'],
      avoidNotes: ['5'],
    },
    minor: {
      scaleName: 'Locrian ♮6',
      keyQuality: 'minor',
      compatibilityScore: 6,
      relationship: 'Diminished mode with natural 6th',
      rationale: 'Locrian with natural 6th from harmonic minor, creating unique diminished sound.',
      musicalContext: 'Defines the ii°7 chord in harmonic minor, with natural 6th providing slight stability.',
      recommendedUse: 'Use over ii°7 chords. The natural 6th distinguishes it from standard Locrian.',
      targetNotes: ['b2', 'b5', '6'],
    },
  },

  'Hungarian Minor': {
    major: {
      scaleName: 'Hungarian Minor',
      keyQuality: 'major',
      compatibilityScore: 4,
      relationship: 'Exotic minor with augmented 2nd',
      rationale: 'Harmonic minor with #4, creating intense Eastern European character.',
      musicalContext: 'Gypsy/Hungarian folk scale with two augmented 2nd intervals.',
      recommendedUse: 'Use for exotic, Eastern European flavor. The #4 and augmented 2nds are signature.',
      targetNotes: ['#4', '7'],
    },
    minor: {
      scaleName: 'Hungarian Minor',
      keyQuality: 'minor',
      compatibilityScore: 7,
      relationship: 'Harmonic minor with raised 4th',
      rationale: 'Harmonic minor with #4, intensifying the exotic character with double augmented 2nds.',
      musicalContext: 'Essential for Hungarian, Gypsy, and klezmer music. Highly distinctive sound.',
      recommendedUse: 'Use for authentic Eastern European minor sound. Emphasize the #4 and augmented intervals.',
      targetNotes: ['#4', 'b6', '7'],
    },
  },

  'Double Harmonic': {
    major: {
      scaleName: 'Double Harmonic',
      keyQuality: 'major',
      compatibilityScore: 5,
      relationship: 'Exotic scale with two augmented 2nds',
      rationale: 'Major scale with b2 and b6, creating Middle Eastern/Byzantine character.',
      musicalContext: 'Arabic/Byzantine scale with symmetrical augmented 2nd intervals.',
      recommendedUse: 'Use for Middle Eastern and Byzantine music. The b2 and b6 create exotic tension.',
      targetNotes: ['b2', '3', 'b6'],
    },
    minor: {
      scaleName: 'Double Harmonic',
      keyQuality: 'minor',
      compatibilityScore: 6,
      relationship: 'Byzantine/Arabic minor scale',
      rationale: 'Creates intense Middle Eastern character with b2, major 3rd, and b6.',
      musicalContext: 'Essential for Arabic maqam and Byzantine chant, with characteristic augmented 2nds.',
      recommendedUse: 'Use for authentic Middle Eastern sound. The augmented 2nds are the signature.',
      targetNotes: ['b2', 'b6', '7'],
    },
  },

  'Whole Tone': {
    major: {
      scaleName: 'Whole Tone',
      keyQuality: 'major',
      compatibilityScore: 6,
      relationship: 'Symmetrical augmented scale',
      rationale: 'Six notes separated by whole steps, creating floating, dreamlike ambiguity.',
      musicalContext: 'Impressionist scale (Debussy), with no perfect 5th creating tonal ambiguity.',
      recommendedUse: 'Use over augmented and dominant chords for impressionist, floating sound. No tonal center.',
      targetNotes: ['2', '#4', 'b7'],
      avoidNotes: ['5'],
    },
    minor: {
      scaleName: 'Whole Tone',
      keyQuality: 'minor',
      compatibilityScore: 4,
      relationship: 'Atonal symmetrical relationship',
      rationale: 'Creates complete tonal ambiguity over minor, lacking the b3 that defines minor quality.',
      musicalContext: 'Experimental use in minor contexts, destroys minor tonality.',
      recommendedUse: 'Use sparingly for atonal, floating passages. Lacks minor character entirely.',
      avoidNotes: ['b3', '5'],
    },
  },

  'Diminished (Half-Whole)': {
    major: {
      scaleName: 'Diminished (Half-Whole)',
      keyQuality: 'major',
      compatibilityScore: 7,
      relationship: 'Symmetrical diminished scale',
      rationale: 'Alternating half and whole steps, perfect for diminished 7th chords.',
      musicalContext: 'Jazz diminished scale, essential for dim7 and tension over dominant chords.',
      recommendedUse: 'Use over dim7 chords. The symmetry allows transposition by minor 3rds.',
      targetNotes: ['b3', 'b5', '6'],
    },
    minor: {
      scaleName: 'Diminished (Half-Whole)',
      keyQuality: 'minor',
      compatibilityScore: 7,
      relationship: 'Diminished chord scale',
      rationale: 'Perfect for diminished 7th chords in minor keys, with symmetrical structure.',
      musicalContext: 'Essential for jazz diminished harmony, works over vii°7 and passing dim7 chords.',
      recommendedUse: 'Use over dim7 chords in minor. Symmetry allows multiple root interpretations.',
      targetNotes: ['1', 'b3', 'b5', '6'],
    },
  },

  'Diminished (Whole-Half)': {
    major: {
      scaleName: 'Diminished (Whole-Half)',
      keyQuality: 'major',
      compatibilityScore: 7,
      relationship: 'Dominant diminished scale',
      rationale: 'Alternating whole and half steps, perfect for dominant 7th chords with tensions.',
      musicalContext: 'Jazz dominant scale, containing all possible dominant tensions (b9, #9, #11, 13).',
      recommendedUse: 'Use over V7 chords. Contains both b9 and #9, plus #11 and 13. Jazz essential.',
      targetNotes: ['3', 'b9', '#9', '#11'],
    },
    minor: {
      scaleName: 'Diminished (Whole-Half)',
      keyQuality: 'minor',
      compatibilityScore: 8,
      relationship: 'Dominant diminished for minor',
      rationale: 'The dominant diminished scale, perfect for V7 chords in minor with all tensions.',
      musicalContext: 'Essential jazz dominant scale for minor keys, with complete tension palette.',
      recommendedUse: 'Primary scale for V7b9 chords in minor. All dominant tensions available.',
      targetNotes: ['3', 'b9', '#11', '13'],
    },
  },

  'Bebop Dominant': {
    major: {
      scaleName: 'Bebop Dominant',
      keyQuality: 'major',
      compatibilityScore: 9,
      relationship: 'Mixolydian with passing tone',
      rationale: 'Mixolydian with added major 7th, creating 8-note scale for bebop phrasing.',
      musicalContext: 'Essential bebop scale, the passing tone allows chord tones on downbeats.',
      recommendedUse: 'Primary scale for V7 chords in bebop. The major 7th is a chromatic passing tone.',
      targetNotes: ['1', '3', '5', 'b7'],
    },
    minor: {
      scaleName: 'Bebop Dominant',
      keyQuality: 'minor',
      compatibilityScore: 8,
      relationship: 'Dominant bebop for minor',
      rationale: 'Mixolydian with major 7th passing tone, perfect for V7 in minor keys.',
      musicalContext: 'Bebop dominant scale for minor, essential for authentic bebop phrasing.',
      recommendedUse: 'Use over V7 chords in minor. The major 7th creates chromatic approach to root.',
      targetNotes: ['3', '5', 'b7', '7'],
    },
  },

  'Bebop Major': {
    major: {
      scaleName: 'Bebop Major',
      keyQuality: 'major',
      compatibilityScore: 9,
      relationship: 'Major scale with passing tone',
      rationale: 'Major scale with added #5, creating 8-note scale for bebop phrasing over major chords.',
      musicalContext: 'Bebop major scale, the #5 passing tone enables chord tones on downbeats.',
      recommendedUse: 'Use over Imaj7 chords in bebop. The #5 is a chromatic passing tone to 6.',
      targetNotes: ['1', '3', '5', '#5'],
    },
    minor: {
      scaleName: 'Bebop Major',
      keyQuality: 'minor',
      compatibilityScore: 5,
      relationship: 'Relative major bebop',
      rationale: 'Creates major tonality over minor with bebop passing tone.',
      musicalContext: 'Use for major color over minor progressions in bebop contexts.',
      recommendedUse: 'Use over bIII chords for bebop phrasing. Creates major-over-minor color.',
      targetNotes: ['bIII', '5'],
    },
  },

  'Bebop Minor': {
    major: {
      scaleName: 'Bebop Minor',
      keyQuality: 'major',
      compatibilityScore: 6,
      relationship: 'Relative minor bebop',
      rationale: 'Dorian with added major 3rd, creating bebop phrasing over minor chords.',
      musicalContext: 'Bebop minor scale for vi chords, with chromatic passing tone.',
      recommendedUse: 'Use over vi chords in bebop. The major 3rd is a chromatic approach to 4.',
      targetNotes: ['6', 'b3', '3'],
    },
    minor: {
      scaleName: 'Bebop Minor',
      keyQuality: 'minor',
      compatibilityScore: 9,
      relationship: 'Dorian with chromatic passing tone',
      rationale: 'Dorian with added major 3rd, essential for bebop phrasing over minor chords.',
      musicalContext: 'Primary bebop minor scale, the major 3rd creates chromatic approach to 4.',
      recommendedUse: 'Use over i and iv chords in bebop. The major 3rd is a chromatic passing tone.',
      targetNotes: ['1', 'b3', '3', '5'],
    },
  },

  'Bebop Dorian': {
    major: {
      scaleName: 'Bebop Dorian',
      keyQuality: 'major',
      compatibilityScore: 7,
      relationship: 'Dorian with major 3rd passing tone',
      rationale: 'Dorian with added major 3rd between minor 3rd and 4th for bebop phrasing.',
      musicalContext: 'Bebop variation of Dorian for ii chords, enabling chord tones on downbeats.',
      recommendedUse: 'Use over ii chords in bebop. The major 3rd creates chromatic connection.',
      targetNotes: ['2', 'b3', '3', '6'],
    },
    minor: {
      scaleName: 'Bebop Dorian',
      keyQuality: 'minor',
      compatibilityScore: 8,
      relationship: 'Bebop Dorian for minor',
      rationale: 'Dorian with major 3rd passing tone, perfect for bebop phrasing in minor contexts.',
      musicalContext: 'Sophisticated bebop minor scale with chromatic approach tone.',
      recommendedUse: 'Use over i chords in bebop minor. The chromatic passing tone enables strong phrasing.',
      targetNotes: ['1', 'b3', '3', '6'],
    },
  },

  'Ionian ♯5': {
    major: {
      scaleName: 'Ionian ♯5',
      keyQuality: 'major',
      compatibilityScore: 6,
      relationship: '3rd mode of harmonic minor',
      rationale: 'Major scale with #5, creating augmented tonality from harmonic minor.',
      musicalContext: 'Theoretical mode with augmented character, rarely used melodically.',
      recommendedUse: 'Use over Imaj7#5 chords. The #5 creates augmented color.',
      targetNotes: ['1', '3', '#5'],
    },
    minor: {
      scaleName: 'Ionian ♯5',
      keyQuality: 'minor',
      compatibilityScore: 4,
      relationship: 'Relative major augmented',
      rationale: 'Creates major augmented tonality over minor, highly experimental.',
      musicalContext: 'Distant relationship, creates augmented major color over minor keys.',
      recommendedUse: 'Use sparingly for augmented color. Very advanced modal interchange.',
      avoidNotes: ['5'],
    },
  },

  'Dorian ♯4': {
    major: {
      scaleName: 'Dorian ♯4',
      keyQuality: 'major',
      compatibilityScore: 6,
      relationship: '4th mode of harmonic minor',
      rationale: 'Dorian with #4, combining minor sophistication with Lydian brightness.',
      musicalContext: 'Harmonic minor mode with unique #4 over minor tonality.',
      recommendedUse: 'Use over ii chords for exotic color. The #4 adds Lydian brightness to Dorian.',
      targetNotes: ['2', '#4', '6'],
    },
    minor: {
      scaleName: 'Dorian ♯4',
      keyQuality: 'minor',
      compatibilityScore: 7,
      relationship: 'Dorian with raised 4th',
      rationale: 'Dorian with #4 from harmonic minor, creating sophisticated minor sound.',
      musicalContext: 'Jazz minor mode with #4 adding brightness to Dorian character.',
      recommendedUse: 'Use over i and iv chords for sophisticated color. The #4 is the signature note.',
      targetNotes: ['1', 'b3', '#4', '6'],
    },
  },

  'Lydian ♯2': {
    major: {
      scaleName: 'Lydian ♯2',
      keyQuality: 'major',
      compatibilityScore: 5,
      relationship: '6th mode of harmonic minor',
      rationale: 'Lydian with #2, creating extreme brightness with two augmented intervals.',
      musicalContext: 'Theoretical mode with double augmented character, rarely used.',
      recommendedUse: 'Use for experimental bright passages. The #2 and #4 create extreme brightness.',
      targetNotes: ['#2', '#4'],
    },
    minor: {
      scaleName: 'Lydian ♯2',
      keyQuality: 'minor',
      compatibilityScore: 3,
      relationship: 'Distant augmented relationship',
      rationale: 'Creates extreme major brightness over minor, highly theoretical.',
      musicalContext: 'Experimental mode, creates major tonality with augmented intervals over minor.',
      recommendedUse: 'Use only for extreme experimental passages. Very advanced technique.',
      avoidNotes: ['2', 'b3'],
    },
  },

  'Mixolydian ♭9 ♭13': {
    major: {
      scaleName: 'Mixolydian ♭9 ♭13',
      keyQuality: 'major',
      compatibilityScore: 6,
      relationship: '7th mode of harmonic minor',
      rationale: 'Mixolydian with b9 and b13, creating dark dominant character.',
      musicalContext: 'Harmonic minor dominant mode, darker than standard Mixolydian.',
      recommendedUse: 'Use over V7b9 chords. The b9 and b13 create dark dominant tension.',
      targetNotes: ['3', 'b9', 'b13'],
    },
    minor: {
      scaleName: 'Mixolydian ♭9 ♭13',
      keyQuality: 'minor',
      compatibilityScore: 7,
      relationship: 'Altered dominant from harmonic minor',
      rationale: 'Provides dark dominant function with b9 and b13 alterations.',
      musicalContext: 'Essential for V7b9 chords in harmonic minor, with characteristic b9.',
      recommendedUse: 'Use over V7b9 chords. The b9 is essential for harmonic minor dominant sound.',
      targetNotes: ['3', 'b9', 'b7'],
    },
  },

  'Aeolian ♭5': {
    major: {
      scaleName: 'Aeolian ♭5',
      keyQuality: 'major',
      compatibilityScore: 5,
      relationship: '6th mode of melodic minor',
      rationale: 'Natural minor with b5, creating unstable minor character.',
      musicalContext: 'Melodic minor mode with diminished 5th, rarely used melodically.',
      recommendedUse: 'Use over vi chords for dark, unstable color. The b5 creates tension.',
      targetNotes: ['6', 'b5'],
      avoidNotes: ['5'],
    },
    minor: {
      scaleName: 'Aeolian ♭5',
      keyQuality: 'minor',
      compatibilityScore: 6,
      relationship: 'Natural minor with diminished 5th',
      rationale: 'Natural minor with b5, creating half-diminished character.',
      musicalContext: 'Defines half-diminished sound in melodic minor contexts.',
      recommendedUse: 'Use over i°7 chords. The b5 creates half-diminished quality.',
      targetNotes: ['1', 'b3', 'b5'],
      avoidNotes: ['5'],
    },
  },

  'Japanese Pentatonic': {
    major: {
      scaleName: 'Japanese Pentatonic',
      keyQuality: 'major',
      compatibilityScore: 6,
      relationship: 'Exotic pentatonic with b2',
      rationale: 'Pentatonic scale with b2, creating Japanese/Asian character.',
      musicalContext: 'Traditional Japanese scale (In Sen), with characteristic b2 and perfect 4th.',
      recommendedUse: 'Use for Japanese/Asian flavor. The b2 and absence of 3rd create exotic sound.',
      targetNotes: ['b2', '4', '5'],
    },
    minor: {
      scaleName: 'Japanese Pentatonic',
      keyQuality: 'minor',
      compatibilityScore: 7,
      relationship: 'Minor pentatonic with b2',
      rationale: 'Creates Japanese character in minor contexts with b2 and b6.',
      musicalContext: 'Traditional Japanese minor sound, essential for authentic Asian music.',
      recommendedUse: 'Perfect for Japanese/Asian minor music. The b2 is the signature interval.',
      targetNotes: ['1', 'b2', '5', 'b6'],
    },
  },

  'Egyptian Pentatonic': {
    major: {
      scaleName: 'Egyptian Pentatonic',
      keyQuality: 'major',
      compatibilityScore: 7,
      relationship: 'Suspended pentatonic',
      rationale: 'Pentatonic with suspended character (no 3rd), creating ancient Middle Eastern sound.',
      musicalContext: 'Ancient scale with suspended tonality, neither major nor minor.',
      recommendedUse: 'Use for Middle Eastern/ancient flavor. The suspended quality creates ambiguity.',
      targetNotes: ['1', '2', '5'],
    },
    minor: {
      scaleName: 'Egyptian Pentatonic',
      keyQuality: 'minor',
      compatibilityScore: 7,
      relationship: 'Suspended minor pentatonic',
      rationale: 'Creates ancient Middle Eastern character with suspended tonality.',
      musicalContext: 'Traditional Middle Eastern scale, works in both major and minor contexts.',
      recommendedUse: 'Use for ancient/Middle Eastern sound. The suspended quality is versatile.',
      targetNotes: ['1', '4', '5', 'b7'],
    },
  },

  'Gypsy': {
    major: {
      scaleName: 'Gypsy',
      keyQuality: 'major',
      compatibilityScore: 4,
      relationship: 'Exotic minor with augmented 2nds',
      rationale: 'Phrygian dominant with b6, creating intense Gypsy/Romani character.',
      musicalContext: 'Traditional Romani scale with two augmented 2nd intervals.',
      recommendedUse: 'Use for authentic Gypsy/Romani flavor. The augmented 2nds are essential.',
      targetNotes: ['b2', '3', 'b6'],
    },
    minor: {
      scaleName: 'Gypsy',
      keyQuality: 'minor',
      compatibilityScore: 6,
      relationship: 'Romani/Gypsy minor scale',
      rationale: 'Traditional Gypsy scale with characteristic augmented 2nd intervals.',
      musicalContext: 'Essential for Romani music, with intense exotic character.',
      recommendedUse: 'Perfect for Gypsy/Romani music. Emphasize the augmented 2nd intervals.',
      targetNotes: ['b2', '3', 'b6', '7'],
    },
  },

  'Persian': {
    major: {
      scaleName: 'Persian',
      keyQuality: 'major',
      compatibilityScore: 4,
      relationship: 'Exotic Middle Eastern scale',
      rationale: 'Major scale with b2, b5, and b6, creating intense Persian character.',
      musicalContext: 'Traditional Persian maqam with unique interval structure.',
      recommendedUse: 'Use for authentic Persian/Middle Eastern music. The b2 and b5 are signature.',
      targetNotes: ['b2', '3', 'b5', 'b6'],
    },
    minor: {
      scaleName: 'Persian',
      keyQuality: 'minor',
      compatibilityScore: 5,
      relationship: 'Persian maqam scale',
      rationale: 'Creates authentic Persian character with b2, b5, and b6.',
      musicalContext: 'Traditional Persian scale, essential for Middle Eastern music.',
      recommendedUse: 'Perfect for Persian/Iranian music. The unique intervals create authentic sound.',
      targetNotes: ['b2', 'b5', 'b6', '7'],
    },
  },

  'Arabic': {
    major: {
      scaleName: 'Arabic',
      keyQuality: 'major',
      compatibilityScore: 4,
      relationship: 'Arabic maqam scale',
      rationale: 'Major scale with b2 and b6, creating Arabic/Middle Eastern character.',
      musicalContext: 'Traditional Arabic maqam with characteristic augmented 2nd.',
      recommendedUse: 'Use for Arabic/Middle Eastern music. The b2 and augmented 2nd are essential.',
      targetNotes: ['b2', '3', 'b6'],
    },
    minor: {
      scaleName: 'Arabic',
      keyQuality: 'minor',
      compatibilityScore: 6,
      relationship: 'Arabic minor maqam',
      rationale: 'Traditional Arabic scale with b2, major 3rd, and b6.',
      musicalContext: 'Essential for Arabic music, with characteristic augmented 2nd intervals.',
      recommendedUse: 'Perfect for Arabic/Middle Eastern music. The augmented 2nds create authentic flavor.',
      targetNotes: ['b2', '3', 'b6', '7'],
    },
  },

  'Byzantine': {
    major: {
      scaleName: 'Byzantine',
      keyQuality: 'major',
      compatibilityScore: 4,
      relationship: 'Byzantine chant scale',
      rationale: 'Double harmonic scale, essential for Byzantine and Greek music.',
      musicalContext: 'Traditional Byzantine chant scale with two augmented 2nd intervals.',
      recommendedUse: 'Use for Byzantine/Greek Orthodox music. The augmented 2nds are signature.',
      targetNotes: ['b2', '3', 'b6', '7'],
    },
    minor: {
      scaleName: 'Byzantine',
      keyQuality: 'minor',
      compatibilityScore: 6,
      relationship: 'Byzantine minor scale',
      rationale: 'Creates authentic Byzantine character with double augmented 2nds.',
      musicalContext: 'Essential for Byzantine chant and Greek music.',
      recommendedUse: 'Perfect for Byzantine/Greek music. The symmetrical augmented 2nds are essential.',
      targetNotes: ['b2', '3', 'b6', '7'],
    },
  },

  'Enigmatic': {
    major: {
      scaleName: 'Enigmatic',
      keyQuality: 'major',
      compatibilityScore: 3,
      relationship: 'Highly experimental scale',
      rationale: 'Theoretical scale with b2, major 3rd, #4, #5, and #6, creating extreme tension.',
      musicalContext: 'Verdi\'s enigmatic scale, rarely used but creates unique mysterious character.',
      recommendedUse: 'Use for experimental, mysterious passages. Extremely advanced technique.',
      targetNotes: ['b2', '#4', '#5', '#6'],
    },
    minor: {
      scaleName: 'Enigmatic',
      keyQuality: 'minor',
      compatibilityScore: 2,
      relationship: 'Theoretical experimental scale',
      rationale: 'Creates extreme tension and mystery, highly theoretical.',
      musicalContext: 'Rarely used experimental scale, creates unique but unstable character.',
      recommendedUse: 'Use only for extreme experimental effects. Very advanced and unstable.',
      avoidNotes: ['2', 'b3', '5', '6'],
    },
  },

  'Neapolitan Minor': {
    major: {
      scaleName: 'Neapolitan Minor',
      keyQuality: 'major',
      compatibilityScore: 4,
      relationship: 'Harmonic minor with b2',
      rationale: 'Harmonic minor with b2, creating dark Neapolitan character.',
      musicalContext: 'Classical scale with Neapolitan (bII) chord emphasis.',
      recommendedUse: 'Use for classical Neapolitan harmony. The b2 creates dark, dramatic character.',
      targetNotes: ['b2', '7'],
    },
    minor: {
      scaleName: 'Neapolitan Minor',
      keyQuality: 'minor',
      compatibilityScore: 7,
      relationship: 'Harmonic minor with Neapolitan 2nd',
      rationale: 'Harmonic minor with b2, essential for Neapolitan sixth chord harmony.',
      musicalContext: 'Classical minor scale emphasizing the Neapolitan (bII) chord.',
      recommendedUse: 'Use for classical minor with Neapolitan harmony. The b2 is the signature note.',
      targetNotes: ['b2', 'b3', '7'],
    },
  },

  'Neapolitan Major': {
    major: {
      scaleName: 'Neapolitan Major',
      keyQuality: 'major',
      compatibilityScore: 5,
      relationship: 'Major scale with b2',
      rationale: 'Major scale with b2, creating Neapolitan character with major tonality.',
      musicalContext: 'Classical scale combining Neapolitan b2 with major quality.',
      recommendedUse: 'Use for Neapolitan harmony in major contexts. The b2 adds classical drama.',
      targetNotes: ['b2', '3', '7'],
    },
    minor: {
      scaleName: 'Neapolitan Major',
      keyQuality: 'minor',
      compatibilityScore: 5,
      relationship: 'Melodic minor with b2',
      rationale: 'Melodic minor with b2, combining Neapolitan and jazz minor characters.',
      musicalContext: 'Hybrid scale with Neapolitan b2 and melodic minor upper structure.',
      recommendedUse: 'Use for sophisticated Neapolitan harmony. Combines classical and jazz elements.',
      targetNotes: ['b2', '6', '7'],
    },
  },

  'Chromatic': {
    major: {
      scaleName: 'Chromatic',
      keyQuality: 'major',
      compatibilityScore: 5,
      relationship: 'All twelve tones',
      rationale: 'Contains all twelve chromatic notes, providing complete tonal palette.',
      musicalContext: 'The complete chromatic scale, foundation of Western equal temperament.',
      recommendedUse: 'Use for chromatic passages and connecting chord tones. All notes available.',
      targetNotes: ['1', '2', '3', '4', '5', '6', '7'],
    },
    minor: {
      scaleName: 'Chromatic',
      keyQuality: 'minor',
      compatibilityScore: 5,
      relationship: 'All twelve tones',
      rationale: 'Contains all twelve chromatic notes, providing complete tonal palette.',
      musicalContext: 'The complete chromatic scale, foundation of Western equal temperament.',
      recommendedUse: 'Use for chromatic passages and connecting chord tones. All notes available.',
      targetNotes: ['1', 'b3', '4', '5', 'b7'],
    },
  },

  'Augmented': {
    major: {
      scaleName: 'Augmented',
      keyQuality: 'major',
      compatibilityScore: 6,
      relationship: 'Symmetrical augmented scale',
      rationale: 'Six-note symmetrical scale built from augmented triads, repeating every major 3rd.',
      musicalContext: 'Hexatonic scale with augmented character, used in impressionist and modern music.',
      recommendedUse: 'Use over augmented chords. The symmetry allows transposition by major 3rds.',
      targetNotes: ['1', '3', '#5'],
    },
    minor: {
      scaleName: 'Augmented',
      keyQuality: 'minor',
      compatibilityScore: 4,
      relationship: 'Augmented symmetrical scale',
      rationale: 'Creates augmented tonality over minor, lacking the b3 that defines minor quality.',
      musicalContext: 'Experimental use in minor, creates augmented ambiguity.',
      recommendedUse: 'Use sparingly for augmented color. Lacks minor character.',
      avoidNotes: ['b3', '5'],
    },
  },
};


