/**
 * Generate Scale Compatibility Data
 * This script generates SQL INSERT statements for the scale_mode_compatibility table
 * Run with: npx ts-node scripts/generateCompatibilityData.ts > sql/migrations/005_seed_compatibility_data.sql
 */

import { NOTES } from '../lib/musicTheory';
import { getCompatibleScales } from '../lib/musical-intelligence/scaleCompatibility';

// All 24 musical keys
const MUSICAL_KEYS = [
  // Major keys
  { keyName: 'C', quality: 'major' as const },
  { keyName: 'C#', quality: 'major' as const },
  { keyName: 'D', quality: 'major' as const },
  { keyName: 'D#', quality: 'major' as const },
  { keyName: 'E', quality: 'major' as const },
  { keyName: 'F', quality: 'major' as const },
  { keyName: 'F#', quality: 'major' as const },
  { keyName: 'G', quality: 'major' as const },
  { keyName: 'G#', quality: 'major' as const },
  { keyName: 'A', quality: 'major' as const },
  { keyName: 'A#', quality: 'major' as const },
  { keyName: 'B', quality: 'major' as const },
  // Minor keys
  { keyName: 'Cm', quality: 'minor' as const },
  { keyName: 'C#m', quality: 'minor' as const },
  { keyName: 'Dm', quality: 'minor' as const },
  { keyName: 'D#m', quality: 'minor' as const },
  { keyName: 'Em', quality: 'minor' as const },
  { keyName: 'Fm', quality: 'minor' as const },
  { keyName: 'F#m', quality: 'minor' as const },
  { keyName: 'Gm', quality: 'minor' as const },
  { keyName: 'G#m', quality: 'minor' as const },
  { keyName: 'Am', quality: 'minor' as const },
  { keyName: 'A#m', quality: 'minor' as const },
  { keyName: 'Bm', quality: 'minor' as const },
];

function escapeString(str: string): string {
  return str.replace(/'/g, "''");
}

function arrayToPostgresArray(arr: string[]): string {
  return `ARRAY[${arr.map(item => `'${escapeString(item)}'`).join(', ')}]`;
}

function numberArrayToPostgresArray(arr: number[]): string {
  return `ARRAY[${arr.join(', ')}]`;
}

console.log('-- Migration: Seed scale_mode_compatibility table');
console.log('-- Description: Generated compatibility data for all musical keys and scales');
console.log('-- Created: 2025-11-05');
console.log('-- Generated by: scripts/generateCompatibilityData.ts');
console.log('');
console.log('-- This file contains compatibility mappings for all 24 musical keys');
console.log('-- Each key has multiple compatible scales/modes with ratings from 1-10');
console.log('');

let totalInserts = 0;

for (const { keyName, quality } of MUSICAL_KEYS) {
  console.log(`-- Compatibility data for ${keyName} ${quality}`);
  
  const compatibleScales = getCompatibleScales(keyName, quality);
  
  for (const scale of compatibleScales) {
    const sql = `INSERT INTO scale_mode_compatibility (
  musical_key_id,
  scale_mode_name,
  root_note,
  compatibility_rating,
  is_primary,
  chord_tones,
  guide_tones,
  musical_context,
  scale_intervals
) VALUES (
  (SELECT id FROM musical_keys WHERE key_name = '${escapeString(keyName)}'),
  '${escapeString(scale.scaleName)}',
  '${escapeString(scale.rootNote)}',
  ${scale.rating},
  ${scale.isPrimary},
  ${arrayToPostgresArray(scale.chordTones)},
  ${arrayToPostgresArray(scale.guideTones)},
  '${escapeString(scale.musicalContext)}',
  ${numberArrayToPostgresArray(scale.scaleIntervals)}
) ON CONFLICT (musical_key_id, scale_mode_name, root_note) DO NOTHING;`;
    
    console.log(sql);
    console.log('');
    totalInserts++;
  }
}

console.log(`-- Total compatibility mappings: ${totalInserts}`);
console.log('-- End of migration');

